version: '3'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: cal
      POSTGRES_USER: riajul
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: cal
      DB_USER: riajul
      DB_PASSWORD: password
    ports:
      - "8000:8000"
    command: ["python", "app/main.py"]

volumes:
  postgres_data:
